### ISSUE TITLE
How to generate F3_entire.segy file

### ISSUE THREAD

**Issue by ice-pice** [crild/facies_net#3]
Hi, 

I have downloaded the F3 offshore demo from this link:[ F3 demo ](https://terranubis.com/datainfo/Netherlands-Offshore-F3-Block-Complete).
This opens up peacefully in OpenDtect.
However, the code provided here expects the data to be converted into one large segy file **F3_entire.segy**. 

When I try to export the data cube using Survey -> Export -> Seismics -> Seg-Y -> 3D. It outputs a .sgy file that's 1.2gb in size. Not sure if this is all the data. 
When I modify the given code to read this newly generated segy file, it gives me the following error:
`ValueError: Invalid dimensions, ilines (631) * xlines (951) * offsets (1) should match the number of traces (600515)`

Guys, any hints on how to obtain the full .segy file? 
Any references, @crild ?
Thanks for making all this publicly available.

**Comment by ice-pice** [comment]
Found em : https://drive.google.com/drive/folders/0B7brcf-eGK8CRUhfRW9rSG91bW8
Thanks for releasing all this @crild

**Comment by warda-rezig** [comment]
Hi, I'm facing the same problem, would you please explain how you fixed it (if so)?

**Comment by dgbpaul** [comment]
@warda-rezig I got the same error when trying to open a seismic volume in SEGY format from F3. It seems segyio cannot handle irregular shaped cubes. F3 has a small corner with no data. When I cut out a small rectangular cube of data from the same volume, I had no problems using segyio. In OpendTect you can copy a cube and 'Add Null Traces'. This fills the empty corner and results in a rectangular cube. If you then export the cube in SEGY format you should be able to use segyio.

**Comment by AmenBargees** [comment]
I got it as a 2 dimension matrix and I used reshape I'm Matlab to get 462by951by651 and its working
